mock:
	mockgen github.com/sopherapps/ckydb/implementations/go-ckydb Controller -destination mocks/controller.go
	mockgen github.com/sopherapps/ckydb/implementations/go-ckydb/internal Storage -destination mocks/storage.go